/**
 * Form Template API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Behavior = 'gigya-login-form' | 'gigya-register-form' | 'gigya-complete-registration-form' | 'gigya-mobile-login-form' | 'gigya-mobile-login-verification' | 'gigya-forgot-password-form' | 'gigya-forgot-password-success-form' | 'gigya-reset-password-form' | 'gigya-reset-password-success-form' | 'gigya-password-change-required-form' | 'gigya-verification-pending-form' | 'gigya-tfa-registration-form' | 'gigya-tfa-verification-form' | 'gigya-verification-sent-form' | 'gigya-update-profile-form' | 'gigya-tfa-edit-form' | 'gigya-change-password-form' | 'gigya-otp-send-code-form' | 'gigya-otp-update-form' | 'gigya-tfa-form';

export const Behavior = {
    LoginForm: 'gigya-login-form' as Behavior,
    RegisterForm: 'gigya-register-form' as Behavior,
    CompleteRegistrationForm: 'gigya-complete-registration-form' as Behavior,
    MobileLoginForm: 'gigya-mobile-login-form' as Behavior,
    MobileLoginVerification: 'gigya-mobile-login-verification' as Behavior,
    ForgotPasswordForm: 'gigya-forgot-password-form' as Behavior,
    ForgotPasswordSuccessForm: 'gigya-forgot-password-success-form' as Behavior,
    ResetPasswordForm: 'gigya-reset-password-form' as Behavior,
    ResetPasswordSuccessForm: 'gigya-reset-password-success-form' as Behavior,
    PasswordChangeRequiredForm: 'gigya-password-change-required-form' as Behavior,
    VerificationPendingForm: 'gigya-verification-pending-form' as Behavior,
    TfaRegistrationForm: 'gigya-tfa-registration-form' as Behavior,
    TfaVerificationForm: 'gigya-tfa-verification-form' as Behavior,
    VerificationSentForm: 'gigya-verification-sent-form' as Behavior,
    UpdateProfileForm: 'gigya-update-profile-form' as Behavior,
    TfaEditForm: 'gigya-tfa-edit-form' as Behavior,
    ChangePasswordForm: 'gigya-change-password-form' as Behavior,
    OtpSendCodeForm: 'gigya-otp-send-code-form' as Behavior,
    OtpUpdateForm: 'gigya-otp-update-form' as Behavior,
    TfaForm: 'gigya-tfa-form' as Behavior
};