/**
 * Form Template API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The value of a condition, including the rule as a JavaScript expression and optional parameters.
 */
export interface ConditionValue { 
    rule?: string;
    params?: { [key: string]: string; };
}