/**
 * Form Template API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The type of condition that can be applied to a container.
 */
export type ConditionType = 'data-condition' | 'data-domains' | 'data-apikeys' | 'data-prob' | 'data-after-date' | 'data-before-date' | 'data-empty-fields' | 'data-login-identities';

export const ConditionType = {
    Condition: 'data-condition' as ConditionType,
    Domains: 'data-domains' as ConditionType,
    Apikeys: 'data-apikeys' as ConditionType,
    Prob: 'data-prob' as ConditionType,
    AfterDate: 'data-after-date' as ConditionType,
    BeforeDate: 'data-before-date' as ConditionType,
    EmptyFields: 'data-empty-fields' as ConditionType,
    LoginIdentities: 'data-login-identities' as ConditionType
};