/**
 * Form Template API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Condition } from './condition';

/**
 * Represents a container that can have multiple conditional visibility rules.
 */
export interface ContainerTemplate { 
    id?: string;
    /**
     * html tag
     */
    tag?: string;
    innerHtml?: string;
    conditions?: Array<Condition>;
}