/**
 * Form Template API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConditionType } from './conditionType';
import { ConditionValue } from './conditionValue';

/**
 * A single conditional rule for a container.
 */
export interface Condition { 
    type?: ConditionType;
    value?: ConditionValue;
}