/**
 * Form Template API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Specific parameters that can modify the behavior of a condition.
 */
export type ConditionParam = 'data-on-render';

export const ConditionParam = {
    DataOnRender: 'data-on-render' as ConditionParam
};