/**
 * Form Template API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Condition } from './condition';
import {ConditionType} from "./conditionType";
import {ConditionValue} from "./conditionValue";

/**
 * Represents a container that can have multiple conditional visibility rules.
 */
export interface ContainerTemplate { 
    id?: string;
    /**
     * html tag
     */
    tag?: string;
    innerHtml?: string;
    conditions?: Array<Condition>;
}

/**
 * A single conditional rule for a container.
 */
export interface Condition {
    type?: ConditionType;
    value?: ConditionValue;
}

/**
 * The type of condition that can be applied to a container.
 */
export type ConditionType = 'data-condition' | 'data-domains' | 'data-apikeys' | 'data-prob' | 'data-after-date' | 'data-before-date' | 'data-empty-fields' | 'data-login-identities';


/**
 * The value of a condition, including the rule as a JavaScript expression and optional parameters.
 */
export interface ConditionValue {
    rule?: string;
    params?: { [key: string]: string; };
}
