/**
 * Form Template API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Screen } from './screen';

export interface ScreenSet { 
    /**
     * A unique identifier for the screen-set.
     */
    id?: string;
    /**
     * CSS style to apply
     */
    css?: string;
    links?: Array<string>;
    /**
     * Enables responsive design for the screen-set.
     */
    dataResponsive?: boolean;
    /**
     * Defines the width of the screen-set when presented in a dialog.
     */
    dataWidth?: number;
    /**
     * Defines the height of the screen-set when presented in a dialog.
     */
    dataHeight?: number;
    /**
     * Specifies the initial screen to display within the screen-set.
     */
    dataStartScreen?: string;
    /**
     * Style of the dialog when the screen-set is presented in a dialog.
     */
    dataDialogStyle?: ScreenSet.DataDialogStyle;
    screens?: Array<Screen>;
}
export namespace ScreenSet {
    export type DataDialogStyle = 'none' | 'classic' | 'modern' | 'legacy';
    export const DataDialogStyleEnum = {
        None: 'none' as DataDialogStyle,
        Classic: 'classic' as DataDialogStyle,
        Modern: 'modern' as DataDialogStyle,
        Legacy: 'legacy' as DataDialogStyle
    };
}